# Generated by Django 4.1.1 on 2022-11-19 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, to='blockso_app.profile'),
        ),
        migrations.CreateModel(
            name='MentionedInPostEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mentioned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockso_app.profile')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_in_post_event', to='blockso_app.notification')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockso_app.post')),
            ],
        ),
    ]
