# Generated by Django 4.1.1 on 2022-11-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0002_post_tagged_users_mentionedinpostevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepostEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repost_event', to='blockso_app.notification')),
                ('repost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockso_app.post')),
                ('reposted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockso_app.profile')),
            ],
        ),
    ]
