# Generated by Django 4.1.1 on 2022-09-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0002_transaction_erc721transfer_erc20transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erc20transfer',
            name='amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
