# Generated by Django 4.1.1 on 2022-09-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0003_alter_erc20transfer_amount_alter_transaction_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgUrl',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='isQuote',
            new_name='is_quote',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='isShare',
            new_name='is_share',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='refPost',
            new_name='ref_post',
        ),
        migrations.AddField(
            model_name='post',
            name='ref_tx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockso_app.transaction'),
        ),
    ]
