# Generated by Django 4.1.1 on 2022-12-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0003_repostevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('day_to_date_count', models.PositiveIntegerField()),
                ('week_to_date_count', models.PositiveIntegerField()),
                ('month_to_date_count', models.PositiveIntegerField()),
            ],
        ),
    ]
