# Generated by Django 4.1.1 on 2022-09-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0004_rename_imgurl_post_img_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_url',
            new_name='imgUrl',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_quote',
            new_name='isQuote',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_share',
            new_name='isShare',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ref_post',
            new_name='refPost',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ref_tx',
            new_name='refTx',
        ),
    ]
