# Generated by Django 4.1.1 on 2022-12-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0005_postlike_likedpostevent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'liker'), name='cannot like a post twice'),
        ),
    ]
