# Generated by Django 4.1.1 on 2022-12-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0006_postlike_cannot_like_a_post_twice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedCommentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockso_app.comment')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockso_app.profile')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liked_comment_event', to='blockso_app.notification')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blockso_app.comment')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='blockso_app.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('comment', 'liker'), name='cannot like a comment twice'),
        ),
    ]
