# Generated by Django 4.1.1 on 2022-12-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0007_likedcommentevent_commentlike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('profiles', models.ManyToManyField(blank=True, to='blockso_app.profile')),
            ],
        ),
    ]
