# Generated by Django 4.1.1 on 2022-09-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0007_delete_user_alter_post_created_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erc721transfer',
            name='token_id',
            field=models.CharField(max_length=255),
        ),
    ]
