# Generated by Django 4.1.1 on 2022-12-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0008_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
