# Generated by Django 4.1.1 on 2023-01-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0009_feed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='successful',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_offset',
        ),
    ]
