# Generated by Django 4.1.1 on 2022-09-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0010_alter_profile_bio_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
