# Generated by Django 4.1.1 on 2023-01-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0010_remove_transaction_successful_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='profiles',
        ),
        migrations.AddField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feed',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='feeds_they_follow', to='blockso_app.profile'),
        ),
        migrations.AddField(
            model_name='feed',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='feeds_following_them', to='blockso_app.profile'),
        ),
        migrations.AddField(
            model_name='feed',
            name='following_editable_by_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feed',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_feeds', to='blockso_app.profile'),
            preserve_default=False,
        ),
    ]
