# Generated by Django 4.1.1 on 2023-01-31 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0011_remove_feed_profiles_feed_description_feed_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='following_editable_by_public',
            new_name='followingEditableByPublic',
        ),
    ]
