# Generated by Django 4.1.1 on 2023-02-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0012_rename_following_editable_by_public_feed_followingeditablebypublic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
