# Generated by Django 4.1.1 on 2022-11-11 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0014_alter_commentonpostevent_commentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_dest', to='blockso_app.profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_src', to='blockso_app.profile'),
        ),
    ]
