# Generated by Django 4.1.1 on 2022-11-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockso_app', '0016_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blockso_app.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, to='blockso_app.profile'),
        ),
    ]
